name: Deploy to AWS Public ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # Public ECR is only in us-east-1

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin public.ecr.aws/q7j8n3l6

      - name: Build, tag, and push image
        run: |
          IMAGE_TAG=latest
          IMAGE_URI=public.ecr.aws/q7j8n3l6/techpro-app:$IMAGE_TAG
          docker build -t techpro-app:$IMAGE_TAG .
          docker tag techpro-app:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI

      #OPTIONAL: Deploy to EC2 via SSH
      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull public.ecr.aws/q7j8n3l6/techpro-app:latest
            docker stop techpro || true
            docker rm techpro || true
            docker run -d -p 80:80 --name techpro public.ecr.aws/q7j8n3l6/techpro-app:latest
